services:
  db:
    image: postgres:17.5-alpine
    restart: no
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: v2i
    profiles:
      - dev
      - prod
      - db

  adminer:
    image: adminer
    restart: no
    ports:
      - "8080:8080"
    profiles:
      - dev
      - db

  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - dev
      - prod

  localstack:
    image: localstack/localstack:4.13.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_DEFAULT_REGION=us-east-1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - S3_ENDPOINT=http://localhost:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh"
    profiles:
      - dev