apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2i-web-deployment-v1
  labels:
    app: v2i-web-deployment-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2i-web
  template:
    metadata:
      labels:
        app: v2i-web
    spec:
      containers:
        - name: v2i-web
          image: hackaton-v2i-web:v4
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: v2i-web-configmap-v1
            - secretRef:
                name: v2i-web-db-secret-v1
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3