spring.application.name=v2i-web
server.port=8000

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:v2i}}
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Queue
spring.rabbitmq.username=${RABBITMQ_USER:root}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:root}

# AWS
aws.region=us-east-1
aws.access-key-id=${AWS_ACCESS_KEY_ID:root}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:root}
aws.s3.bucket-name=${AWS_BUCKET_NAME:v2i-bucket}
aws.s3.endpoint=${AWS_S3_ENDPOINT:http://127.0.0.1:4566}

#Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.db.enabled=true

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
